language: c
sudo: true

install:
  - wget https://github.com/zeromq/czmq/archive/v3.0.2.tar.gz
  - tar -xzvf v3.0.2.tar.gz
  - cd czmq-3.0.2 && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install
  - wget http://www.lttng.org/files/urcu/userspace-rcu-0.9.1.tar.bz2
  - tar -xjvf userspace-rcu-0.9.1.tar.bz2
  - cd userspace-rcu-0.9.1 && ./configure --prefix=/usr && make && sudo make install
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.7.tar.gz
  - tar -xvzf libsodium-1.0.7.tar.gz
  - cd libsodium-1.0.7 && ./configure && sudo make install


  
compiler:
  - gcc
  
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wget build-essential libtool automake pkg-config libjson0-dev libzmq3-dev
  
script:
  - ./c/boot.sh
  - ./c/configure && make
  
after_success:
  - bash <(curl -s https://codecov.io/bash)