################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_JSON-C "json-c")
    if (NOT PC_JSON-C_FOUND)
        pkg_check_modules(PC_JSON-C "json-c")
    endif (NOT PC_JSON-C_FOUND)
    if (PC_JSON-C_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_JSON-C_CFLAGS} ${PC_JSON-C_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_JSON-C_INCLUDE_HINTS ${PC_JSON-C_INCLUDE_DIRS} ${PC_JSON-C_INCLUDE_DIRS}/*)
        set(PC_JSON-C_LIBRARY_HINTS ${PC_JSON-C_LIBRARY_DIRS} ${PC_JSON-C_LIBRARY_DIRS}/*)
    endif(PC_JSON-C_FOUND)
endif (NOT MSVC)

find_path (
    JSON-C_INCLUDE_DIRS
    NAMES json-c/json.h
    HINTS ${PC_JSON-C_INCLUDE_HINTS}
)

find_library (
    JSON-C_LIBRARIES
    NAMES json-c
    HINTS ${PC_JSON-C_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    JSON-C
    REQUIRED_VARS JSON-C_LIBRARIES JSON-C_INCLUDE_DIRS
)
mark_as_advanced(
    JSON-C_FOUND
    JSON-C_LIBRARIES JSON-C_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
