################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################

if (NOT MSVC)
    include(FindPkgConfig)
    pkg_check_modules(PC_URCU-CDS "urcu-cds")
    if (NOT PC_URCU-CDS_FOUND)
        pkg_check_modules(PC_URCU-CDS "urcu-cds")
    endif (NOT PC_URCU-CDS_FOUND)
    if (PC_URCU-CDS_FOUND)
        # add CFLAGS from pkg-config file, e.g. draft api.
        add_definitions(${PC_URCU-CDS_CFLAGS} ${PC_URCU-CDS_CFLAGS_OTHER})
        # some libraries install the headers is a subdirectory of the include dir
        # returned by pkg-config, so use a wildcard match to improve chances of finding
        # headers and SOs.
        set(PC_URCU-CDS_INCLUDE_HINTS ${PC_URCU-CDS_INCLUDE_DIRS} ${PC_URCU-CDS_INCLUDE_DIRS}/*)
        set(PC_URCU-CDS_LIBRARY_HINTS ${PC_URCU-CDS_LIBRARY_DIRS} ${PC_URCU-CDS_LIBRARY_DIRS}/*)
    endif(PC_URCU-CDS_FOUND)
endif (NOT MSVC)

find_path (
    URCU-CDS_INCLUDE_DIRS
    NAMES urcu/cds.h
    HINTS ${PC_URCU-CDS_INCLUDE_HINTS}
)

find_library (
    URCU-CDS_LIBRARIES
    NAMES urcu-cds
    HINTS ${PC_URCU-CDS_LIBRARY_HINTS}
)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(
    URCU-CDS
    REQUIRED_VARS URCU-CDS_LIBRARIES URCU-CDS_INCLUDE_DIRS
)
mark_as_advanced(
    URCU-CDS_FOUND
    URCU-CDS_LIBRARIES URCU-CDS_INCLUDE_DIRS
)

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
