/*----------------------------------------------------------------------
 * This file is generated by mk_parser.py.
 *----------------------------------------------------------------------*/
#ifndef __CPARSER_TREE_H__
#define __CPARSER_TREE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

extern cparser_node_t cparser_root;

cparser_result_t
cparser_cmd_show_subscriptions(cparser_context_t *context);
cparser_result_t cparser_cmd_show_status(cparser_context_t *context);
cparser_result_t cparser_cmd_show_keys(cparser_context_t *context);
cparser_result_t
cparser_cmd_subscribe_topic_scope(cparser_context_t *context,
                                  char **topic_ptr, char **scope_ptr);
cparser_result_t
cparser_cmd_no_subscribe_topic_scope(cparser_context_t *context,
                                     char **topic_ptr, char **scope_ptr);
cparser_result_t
cparser_cmd_publish_topic_message(cparser_context_t *context,
                                  char **topic_ptr, char **message_ptr);
cparser_result_t
cparser_cmd_notify_destination_message(cparser_context_t *context,
                                       char **destination_ptr,
                                       char **message_ptr);
cparser_result_t cparser_cmd_quit(cparser_context_t *context);
cparser_result_t cparser_cmd_help(cparser_context_t *context);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* __CPARSER_TREE_H__ */
