/*  =========================================================================
    doubledecker - generated layer of public API

        Copyright (c) 2015 Pontus Sköldström, Bertrand Pechenot           
                                                                            
        This file is part of libdd, the DoubleDecker hierarchical           
        messaging system DoubleDecker is free software; you can             
        redistribute it and/or modify it under the terms of the GNU Lesser  
        General Public License (LGPL) version 2.1 as published by the Free  
        Software Foundation.                                                
                                                                            
        As a special exception, the Authors give you permission to link this
        library with independent modules to produce an executable,          
        regardless of the license terms of these independent modules, and to
        copy and distribute the resulting executable under terms of your    
        choice, provided that you also meet, for each linked independent    
        module, the terms and conditions of the license of that module. An  
        independent module is a module which is not derived from or based on
        this library.  If you modify this library, you must extend this     
        exception to your version of the library.  DoubleDecker is          
        distributed in the hope that it will be useful, but WITHOUT ANY     
        WARRANTY; without even the implied warranty of MERCHANTABILITY or   
        FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public 
        License for more details.  You should have received a copy of the   
        GNU Lesser General Public License along with this program.  If not, 
        see http://www.gnu.org/licenses/.                                   

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef DD_LIBRARY_H_INCLUDED
#define DD_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <sodium.h>
#include <json-c/json.h>
#include <urcu.h>
#include <urcu/cds.h>

//  DD version macros for compile-time API detection
#define DD_VERSION_MAJOR 0
#define DD_VERSION_MINOR 5
#define DD_VERSION_PATCH 0

#define DD_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define DD_VERSION \
    DD_MAKE_VERSION(DD_VERSION_MAJOR, DD_VERSION_MINOR, DD_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined DD_STATIC
#       define DD_EXPORT
#   elif defined DD_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define DD_EXPORT __declspec(dllexport)
#       else
#           define DD_EXPORT
#       endif
#   elif defined DD_EXPORTS
#       define DD_EXPORT __declspec(dllexport)
#   else
#       define DD_EXPORT __declspec(dllimport)
#   endif
#else
#   define DD_EXPORT
#endif

//  Project has no stable classes, so we build the draft API
#undef  DD_BUILD_DRAFT_API
#define DD_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases
//  Draft classes are by default not built in stable releases
#ifdef DD_BUILD_DRAFT_API
typedef struct _dd_broker_t dd_broker_t;
#define DD_BROKER_T_DEFINED
typedef struct _dd_client_t dd_client_t;
#define DD_CLIENT_T_DEFINED
typedef struct _dd_keys_t dd_keys_t;
#define DD_KEYS_T_DEFINED
typedef struct _dd_topic_t dd_topic_t;
#define DD_TOPIC_T_DEFINED
typedef struct _dd_client_actor_t dd_client_actor_t;
#define DD_CLIENT_ACTOR_T_DEFINED
#endif // DD_BUILD_DRAFT_API

//  Public constants
#ifdef DD_BUILD_DRAFT_API
#define DD_STATE_UNREG      1                  //  
#define DD_STATE_ROOT       2                  //  
#define DD_STATE_EXIT       3                  //  
#define DD_STATE_CHALLENGED  4                 //  
#define DD_STATE_REGISTERED  5                 //  
#define DD_ERROR_REGFAIL    1                  //  
#define DD_ERROR_NODST      2                  //  
#define DD_ERROR_VERSION    3                  //  
#define DD_ERROR_TOPIC      4                  //  
#define DD_PRO_VERSION      218955780          //  
#define MAXTENANTNAME       256                //  
#define XXHSEED             123123             //  
#endif // DD_BUILD_DRAFT_API

//  Public classes, each with its own header file
#ifdef DD_BUILD_DRAFT_API
#include "dd_broker.h"
#include "dd_client.h"
#include "dd_keys.h"
#include "dd_topic.h"
#include "dd_client_actor.h"
#endif // DD_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
