/*  =========================================================================
    dd_topic - class description

    Copyright (c) the Contributors as noted in the AUTHORS file.       
    This file is part of CZMQ, the high-level C binding for 0MQ:       
    http://czmq.zeromq.org.                                            
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef DD_TOPIC_H_INCLUDED
#define DD_TOPIC_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/dd_topic.xml" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef DD_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Create a new topic object
DD_EXPORT dd_topic_t *
    dd_topic_new (void);

//  *** Draft method, for development use, may change without warning ***
//  Destroy a topic object
DD_EXPORT void
    dd_topic_destroy (dd_topic_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  
DD_EXPORT const char *
    dd_topic_get_topic (dd_topic_t *self);

//  *** Draft method, for development use, may change without warning ***
//  
DD_EXPORT const char *
    dd_topic_get_scope (dd_topic_t *self);

//  *** Draft method, for development use, may change without warning ***
//  
DD_EXPORT bool
    dd_topic_get_active (dd_topic_t *self);

//  *** Draft method, for development use, may change without warning ***
//  
DD_EXPORT void
    dd_topic_set_topic (dd_topic_t *self, const char *topic);

//  *** Draft method, for development use, may change without warning ***
//  
DD_EXPORT void
    dd_topic_set_scope (dd_topic_t *self, const char *scope);

//  *** Draft method, for development use, may change without warning ***
//  
DD_EXPORT void
    dd_topic_set_active (dd_topic_t *self, bool active);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
DD_EXPORT void
    dd_topic_test (bool verbose);

#endif // DD_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
