/*  =========================================================================
    dist_client - DoubleDecker distant client class

        Copyright (c) 2015 Pontus Sköldström, Bertrand Pechenot           
                                                                            
        This file is part of libdd, the DoubleDecker hierarchical           
        messaging system DoubleDecker is free software; you can             
        redistribute it and/or modify it under the terms of the GNU Lesser  
        General Public License (LGPL) version 2.1 as published by the Free  
        Software Foundation.                                                
                                                                            
        As a special exception, the Authors give you permission to link this
        library with independent modules to produce an executable,          
        regardless of the license terms of these independent modules, and to
        copy and distribute the resulting executable under terms of your    
        choice, provided that you also meet, for each linked independent    
        module, the terms and conditions of the license of that module. An  
        independent module is a module which is not derived from or based on
        this library.  If you modify this library, you must extend this     
        exception to your version of the library.  DoubleDecker is          
        distributed in the hope that it will be useful, but WITHOUT ANY     
        WARRANTY; without even the implied warranty of MERCHANTABILITY or   
        FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public 
        License for more details.  You should have received a copy of the   
        GNU Lesser General Public License along with this program.  If not, 
        see http://www.gnu.org/licenses/.                                   
    =========================================================================
*/

#ifndef DIST_CLIENT_H_INCLUDED
#define DIST_CLIENT_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _dist_client_t dist_client_t;
#define DIST_CLIENT_TAG 0x0d0d0d11
//  Structure of our class
#include "tommy.h"
struct _dist_client_t {
  unsigned int tag;
  char *name; /* Node content */
  zframe_t *broker;
  int distance;
  tommy_node string_node;
  //struct cds_lfht_node node; /* Chaining in hash table */
};
typedef struct json_object json_object_t;

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/dist_client.xml" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef DD_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Create a new distant client
DD_EXPORT dist_client_t *
    dist_client_new (const char *name, zframe_t *broker, int distance);

//  *** Draft method, for development use, may change without warning ***
//  Destroy a distant client
DD_EXPORT void
    dist_client_destroy (dist_client_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Probe the supplied object, and report if it looks like a dd_dist_client_t.
DD_EXPORT bool
    dist_client_is (void *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the full name of this client
DD_EXPORT const char *
    dist_client_get_name (dist_client_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the broker sockid
DD_EXPORT zframe_t *
    dist_client_get_broker (dist_client_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the distance of this client
DD_EXPORT int
    dist_client_get_distance (dist_client_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the hash value of this distant client
DD_EXPORT uint32_t
    dist_client_hash (dist_client_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Convert the object to JSON and return
//  Caller owns return value and must destroy it when done.
DD_EXPORT json_object_t *
    dist_client_json (dist_client_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the full name of this client
DD_EXPORT void
    dist_client_set_name (dist_client_t *self, const char *name);

//  *** Draft method, for development use, may change without warning ***
//  Set the broker sockid
DD_EXPORT void
    dist_client_set_broker (dist_client_t *self, zframe_t *sockid);

//  *** Draft method, for development use, may change without warning ***
//  Set the distance of this client
DD_EXPORT void
    dist_client_set_distance (dist_client_t *self, int distance);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
DD_EXPORT void
    dist_client_test (bool verbose);

#endif // DD_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
