/*  =========================================================================
    local_broker - DoubleDecker local broker class

        Copyright (c) 2015 Pontus Sköldström, Bertrand Pechenot           
                                                                            
        This file is part of libdd, the DoubleDecker hierarchical           
        messaging system DoubleDecker is free software; you can             
        redistribute it and/or modify it under the terms of the GNU Lesser  
        General Public License (LGPL) version 2.1 as published by the Free  
        Software Foundation.                                                
                                                                            
        As a special exception, the Authors give you permission to link this
        library with independent modules to produce an executable,          
        regardless of the license terms of these independent modules, and to
        copy and distribute the resulting executable under terms of your    
        choice, provided that you also meet, for each linked independent    
        module, the terms and conditions of the license of that module. An  
        independent module is a module which is not derived from or based on
        this library.  If you modify this library, you must extend this     
        exception to your version of the library.  DoubleDecker is          
        distributed in the hope that it will be useful, but WITHOUT ANY     
        WARRANTY; without even the implied warranty of MERCHANTABILITY or   
        FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public 
        License for more details.  You should have received a copy of the   
        GNU Lesser General Public License along with this program.  If not, 
        see http://www.gnu.org/licenses/.                                   
    =========================================================================
*/

#ifndef LOCAL_BROKER_H_INCLUDED
#define LOCAL_BROKER_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _local_broker_t local_broker_t;
#define LOCAL_BROKER_TAG  0x45275846
//  Structure of our class

struct _local_broker_t {
  uint32_t tag;
  zframe_t *sockid;
  zframe_t *cookie;
  int distance;
  int timeout;
  //struct cds_lfht_node node;
  tommy_node node;
};

//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT
//  @warning Please edit the model at "api/local_broker.xml" to make changes.
//  @interface
//  This API is a draft, and may change without notice.
#ifdef DD_BUILD_DRAFT_API
//  *** Draft method, for development use, may change without warning ***
//  Create a new local broker
DD_EXPORT local_broker_t *
    local_broker_new (zframe_t *sockid, zframe_t *cookie, int distance);

//  *** Draft method, for development use, may change without warning ***
//  Destroy a local broker
DD_EXPORT void
    local_broker_destroy (local_broker_t **self_p);

//  *** Draft method, for development use, may change without warning ***
//  Probe the supplied object, and report if it looks like a dd_local_broker_t.
DD_EXPORT bool
    local_broker_is (void *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the cookie of this local broker
DD_EXPORT uint64_t
    local_broker_get_cookie (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the socket id of this local broker
DD_EXPORT zframe_t *
    local_broker_get_sockid (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the timeout value for local broker
DD_EXPORT int
    local_broker_get_timeout (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the distance for local broker
DD_EXPORT int
    local_broker_get_distance (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Get the hash value of this local broker
DD_EXPORT uint32_t
    local_broker_hash (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Set the cookie of this local broker
DD_EXPORT void
    local_broker_set_cookie (local_broker_t *self, uint64_t cookie);

//  *** Draft method, for development use, may change without warning ***
//  Set the cookie of this local broker
DD_EXPORT void
    local_broker_set_cookie_zframe (local_broker_t *self, zframe_t *cookie);

//  *** Draft method, for development use, may change without warning ***
//  Set the socket id of this local broker
DD_EXPORT void
    local_broker_set_sockid (local_broker_t *self, zframe_t *sockid);

//  *** Draft method, for development use, may change without warning ***
//  Reset the timeout value for local broker
DD_EXPORT void
    local_broker_reset_timeout (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Increment the timeout value for local broker
DD_EXPORT int
    local_broker_increment_timeout (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Check if the local broker has timed out
DD_EXPORT bool
    local_broker_timed_out (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Returns the JSON represenation of the object
//  Caller owns return value and must destroy it when done.
DD_EXPORT json_object_t *
    local_broker_json (local_broker_t *self);

//  *** Draft method, for development use, may change without warning ***
//  Self test of this class.
DD_EXPORT void
    local_broker_test (bool verbose);

#endif // DD_BUILD_DRAFT_API
//  @end

#ifdef __cplusplus
}
#endif

#endif
